-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Asiakas CASCADE;
DROP TABLE IF EXISTS Viesti CASCADE;
DROP TABLE IF EXISTS EsittelysivuJulkinen CASCADE;
DROP TABLE IF EXISTS EsittelysivuSalainen CASCADE;